from setuptools import setup, find_packages

packages = find_packages(
    where='.',
    include=['ram_utils*']
)
with open("README.md", "r", encoding="utf-8") as f:
    long_description = f.read()

setup(
    name='ram_utils',
    version='0.0.1',
    author='Sigdel Shree Ram',
    author_email='shreeramsigdel77@gmail.com',
    description='Utilities packages',
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/shreeramsigdel77/ram_utils.git",
    packages=packages,
    classfifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    install_requires=[
        'numpy>=1.18.0',
        'opencv-python>=4.2.0.0',
        'pylint>=2.4.2',       
        'Pillow>=6.1.0',
        'pycocotools>=2.0.0',
        "albumentations @ git+https://github.com/albumentations-team/albumentations.git",
        "absl-py==0.12.0",
        # albumentations==0.5.2
        "cachetools==4.2.1",
        "certifi==2020.12.5",
        "chardet==4.0.0",
        "cycler==0.10.0",
        "decorator==4.4.2",
        "google-auth==1.28.0",
        "google-auth-oauthlib==0.4.4",
        "grpcio==1.36.1",
        "idna==2.10",
        "imageio==2.9.0",
        "imgaug==0.4.0",
        "importlib-metadata==3.10.0",
        "imutils==0.5.4",
        "kiwisolver==1.3.1",
        "Markdown==3.3.4",
        "matplotlib==3.4.1",
        "natsort==7.1.1",
        "networkx==2.5.1",
        "oauthlib==3.1.0",
        "pandas==1.2.3",       
        "protobuf==3.15.7",
        "pyasn1==0.4.8",
        "pyasn1-modules==0.2.8",
        "pyparsing==2.4.7",
        "python-dateutil==2.8.1",
        "pytz==2021.1",
        "PyWavelets==1.1.1",
        "PyYAML==5.4.1",
        "requests==2.25.1",
        "requests-oauthlib==1.3.0",
        "rsa==4.7.2",
        "scikit-image==0.18.1",
        "scipy==1.6.2",
        "Shapely==1.7.1",
        "six==1.15.0",
        "tensorboard==2.4.1",
        "tensorboard-plugin-wit==1.8.0",
        "tifffile==2021.3.31",
        "torch==1.8.1",
        "torchaudio==0.8.1",
        "torchsummary==1.5.1",
        "torchvision==0.9.1",
        "typing-extensions==3.7.4.3",
        "urllib3==1.26.4",
        "Werkzeug==1.0.1",
        "zipp==3.4.1",

        # "kkimgaug @ git+https://github.com/kazukingh01/kkimgaug.git",
    ],
    python_requires='>=3.7',

    
)